<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FluentCommandLine\FluentCommandLine.csproj" />
      <ProjectReference Include="..\JWCFarm\JWCFarm.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="TruthInTheFlip.Format">
            <HintPath>..\..\TruthInTheFlip.Dev\TruthInTheFlip.Format\bin\Debug\net10.0\TruthInTheFlip.Format.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
